//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_PHUONGXA
    {
        public int PhuongXaID { get; set; }
        public string PhuongXaName { get; set; }
        public string PhuongXaCode { get; set; }
        public Nullable<int> QuanHuyenID { get; set; }
    
        public virtual DIC_QUANHUYEN DIC_QUANHUYEN { get; set; }
    }
}
