//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_TINHTHANHPHO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIC_TINHTHANHPHO()
        {
            this.DIC_QUANHUYEN = new HashSet<DIC_QUANHUYEN>();
        }
    
        public int TinhThanhPhoID { get; set; }
        public string TinhThanhPhoName { get; set; }
        public string TinhThanhPhoCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIC_QUANHUYEN> DIC_QUANHUYEN { get; set; }
    }
}
