//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_DEGREE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIC_DEGREE()
        {
            this.DIC_POSITION_DEGREE = new HashSet<DIC_POSITION_DEGREE>();
            this.HRM_EMPLOYEE_DEGREE = new HashSet<HRM_EMPLOYEE_DEGREE>();
        }
    
        public int DegreeID { get; set; }
        public string DegreeName { get; set; }
        public string Description { get; set; }
        public string Unclos { get; set; }
        public Nullable<int> WarningBefore { get; set; }
        public Nullable<int> STT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIC_POSITION_DEGREE> DIC_POSITION_DEGREE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRM_EMPLOYEE_DEGREE> HRM_EMPLOYEE_DEGREE { get; set; }
    }
}
