//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_POSITION_DEGREE
    {
        public int PositionDegreeID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<int> DegreeID { get; set; }
    
        public virtual DIC_DEGREE DIC_DEGREE { get; set; }
        public virtual DIC_POSITION DIC_POSITION { get; set; }
    }
}
