//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_SYMBOL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIC_SYMBOL()
        {
            this.HRM_TIMEKEEPER = new HashSet<HRM_TIMEKEEPER>();
        }
    
        public int SymbolID { get; set; }
        public string SymbolCode { get; set; }
        public string SymbolName { get; set; }
        public Nullable<double> PercentSalary { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRM_TIMEKEEPER> HRM_TIMEKEEPER { get; set; }
    }
}
