//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_DEPARTMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIC_DEPARTMENT()
        {
            this.DIC_DEPARTMENT_POSITION = new HashSet<DIC_DEPARTMENT_POSITION>();
            this.HoSoTaus = new HashSet<HoSoTau>();
            this.HRM_DETAILPLAN = new HashSet<HRM_DETAILPLAN>();
            this.HRM_EMPLOYMENTHISTORY = new HashSet<HRM_EMPLOYMENTHISTORY>();
            this.HRM_EMPLOYMENTHISTORY1 = new HashSet<HRM_EMPLOYMENTHISTORY>();
            this.HRM_QTCT = new HashSet<HRM_QTCT>();
            this.HRM_QTCT1 = new HashSet<HRM_QTCT>();
            this.LichKiemTras = new HashSet<LichKiemTra>();
        }
    
        public int DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> FactQuantity { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsLast { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Gross { get; set; }
        public string Power { get; set; }
        public Nullable<int> TypeOfVessel { get; set; }
        public string IMO { get; set; }
        public string Length { get; set; }
        public string Breadth { get; set; }
        public string Draft { get; set; }
        public string DeadWeight { get; set; }
        public string Net { get; set; }
        public Nullable<int> YearOfBuilding { get; set; }
        public string PlaceOfBuiding { get; set; }
        public string PortOfRegistry { get; set; }
        public string ClassificationAgency { get; set; }
        public Nullable<int> ThuTuPhongBan { get; set; }
        public Nullable<bool> IsUsed { get; set; }
    
        public virtual DIC_LOAITAU DIC_LOAITAU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIC_DEPARTMENT_POSITION> DIC_DEPARTMENT_POSITION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoSoTau> HoSoTaus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRM_DETAILPLAN> HRM_DETAILPLAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRM_EMPLOYMENTHISTORY> HRM_EMPLOYMENTHISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRM_EMPLOYMENTHISTORY> HRM_EMPLOYMENTHISTORY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRM_QTCT> HRM_QTCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRM_QTCT> HRM_QTCT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichKiemTra> LichKiemTras { get; set; }
    }
}
