//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_ALLOWANCE
    {
        public string AllowanceCode { get; set; }
        public string AllowanceName { get; set; }
        public Nullable<decimal> MaximumMoney { get; set; }
        public Nullable<bool> IsByWorkDay { get; set; }
        public Nullable<double> IncomeTaxValue { get; set; }
        public Nullable<bool> IsShowInSalaryTableList { get; set; }
        public string Description { get; set; }
    }
}
