//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_ACCIDENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIC_ACCIDENT()
        {
            this.HRM_EMPLOYEE_ACCIDENT = new HashSet<HRM_EMPLOYEE_ACCIDENT>();
        }
    
        public int AccidentID { get; set; }
        public Nullable<System.DateTime> TimeOccurs { get; set; }
        public string Address { get; set; }
        public string Info { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRM_EMPLOYEE_ACCIDENT> HRM_EMPLOYEE_ACCIDENT { get; set; }
    }
}
