//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_MACHINE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIC_MACHINE()
        {
            this.HRM_ATTLOG = new HashSet<HRM_ATTLOG>();
            this.HRM_TIMEKEEPER = new HashSet<HRM_TIMEKEEPER>();
            this.HRM_TIMEKEEPER1 = new HashSet<HRM_TIMEKEEPER>();
        }
    
        public int MachineID { get; set; }
        public string MachineName { get; set; }
        public string PortType { get; set; }
        public string PortID { get; set; }
        public string IP { get; set; }
        public string Password { get; set; }
        public string Com { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRM_ATTLOG> HRM_ATTLOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRM_TIMEKEEPER> HRM_TIMEKEEPER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRM_TIMEKEEPER> HRM_TIMEKEEPER1 { get; set; }
    }
}
