//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_INFORMATIC
    {
        public string InformaticCode { get; set; }
        public string InformaticName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
