//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DieuDongBacThang
    {
        public int DieuDongBacThangID { get; set; }
        public string Tau { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public string NguoiDangDi { get; set; }
        public Nullable<int> NguoiDangDiID { get; set; }
        public Nullable<System.DateTime> NgayLenTau { get; set; }
        public Nullable<int> ThangDiTau { get; set; }
        public string NguoiThayThe { get; set; }
        public Nullable<int> NguoiThayTheID { get; set; }
        public Nullable<System.DateTime> NgayThayThe { get; set; }
        public Nullable<int> ThangDiTauThayThe { get; set; }
    }
}
