//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoSoTau
    {
        public int HoSoTauID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> ChungChiID { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public string FileDinhKem { get; set; }
        public string NoiCap { get; set; }
        public string SoHoSo { get; set; }
        public byte[] fileHoSo { get; set; }
    
        public virtual ChungChiTau ChungChiTau { get; set; }
        public virtual DIC_DEPARTMENT DIC_DEPARTMENT { get; set; }
    }
}
