//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_ACCIDENT
    {
        public int AccidentID { get; set; }
        public Nullable<System.DateTime> AccidentDate { get; set; }
        public string Victim { get; set; }
        public string Place { get; set; }
        public string Reason { get; set; }
        public string Effect { get; set; }
        public string Witness { get; set; }
        public string Solve { get; set; }
        public string Note { get; set; }
    }
}
