//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_SALARYMONTH
    {
        public int HRM_SalaryID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string Position { get; set; }
        public Nullable<int> GroupSalary { get; set; }
        public Nullable<double> Salary { get; set; }
        public Nullable<double> AllowanceSalary { get; set; }
        public Nullable<double> Bonus { get; set; }
        public Nullable<double> AllowanceBonus { get; set; }
        public Nullable<int> NumOfDay { get; set; }
        public Nullable<double> TruKhac { get; set; }
        public string GhiChu { get; set; }
    }
}
