//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_TIMEKEEPER_TABLELIST
    {
        public int TimeKeeperTableListID { get; set; }
        public string TimeKeeperTableListName { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<bool> IsLock { get; set; }
        public Nullable<bool> IsFinish { get; set; }
    }
}
