//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_EMPLOYMENTHISTORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HRM_EMPLOYMENTHISTORY()
        {
            this.HRM_QTCT = new HashSet<HRM_QTCT>();
        }
    
        public int EmploymentHistoryID { get; set; }
        public Nullable<System.DateTime> DecisionDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string ContentDecision { get; set; }
        public Nullable<int> CategoryDecisionID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<int> InternshipPosition { get; set; }
        public Nullable<int> PluralityID { get; set; }
        public Nullable<int> IntershipPlurality { get; set; }
        public string Note { get; set; }
        public Nullable<int> PerPosition { get; set; }
        public Nullable<int> PerPlurality { get; set; }
        public Nullable<int> SalaryPositionID { get; set; }
        public Nullable<int> SalaryPluralityID { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> LoaiTauID { get; set; }
        public string Gross { get; set; }
        public string Power { get; set; }
        public Nullable<System.DateTime> NgayXuongTau { get; set; }
        public Nullable<bool> XacNhan { get; set; }
        public Nullable<int> DecisionNo { get; set; }
        public Nullable<int> DepartmentPluralityID { get; set; }
        public Nullable<int> LyDoNghiViec_ID { get; set; }
        public Nullable<double> Salary { get; set; }
        public Nullable<double> AllowanceSalary { get; set; }
        public Nullable<double> Bonus { get; set; }
        public Nullable<double> AllowanceBonus { get; set; }
        public Nullable<double> SalaryPlurality { get; set; }
        public Nullable<double> AllowanceSalaryPlurality { get; set; }
        public Nullable<double> BonusPlurality { get; set; }
        public Nullable<double> AllowanceBonusPlurality { get; set; }
        public string ThoiGianThucTap { get; set; }
    
        public virtual DIC_CATEGORYDECISION DIC_CATEGORYDECISION { get; set; }
        public virtual DIC_DEPARTMENT DIC_DEPARTMENT { get; set; }
        public virtual DIC_DEPARTMENT DIC_DEPARTMENT1 { get; set; }
        public virtual DIC_INTERSHIP DIC_INTERSHIP { get; set; }
        public virtual DIC_INTERSHIP DIC_INTERSHIP1 { get; set; }
        public virtual DIC_LOAITAU DIC_LOAITAU { get; set; }
        public virtual DIC_POSITION DIC_POSITION { get; set; }
        public virtual DIC_POSITION DIC_POSITION1 { get; set; }
        public virtual DIC_POSITION DIC_POSITION2 { get; set; }
        public virtual DIC_SALARY DIC_SALARY { get; set; }
        public virtual DIC_SALARY DIC_SALARY1 { get; set; }
        public virtual HRM_EMPLOYEE HRM_EMPLOYEE { get; set; }
        public virtual tbl_LyDoNghiViec tbl_LyDoNghiViec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRM_QTCT> HRM_QTCT { get; set; }
    }
}
