//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_EMPLOYEE_DEGREE
    {
        public int EmployeeDegreeID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<int> DegreeID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public string DegreeNo { get; set; }
        public Nullable<System.DateTime> DegreeDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string Qualification { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> IsBC { get; set; }
    
        public virtual DIC_DEGREE DIC_DEGREE { get; set; }
        public virtual DIC_POSITION DIC_POSITION { get; set; }
        public virtual DIC_SCHOOL DIC_SCHOOL { get; set; }
        public virtual HRM_EMPLOYEE HRM_EMPLOYEE { get; set; }
        public virtual HRM_EMPLOYEE_DEGREE HRM_EMPLOYEE_DEGREE1 { get; set; }
        public virtual HRM_EMPLOYEE_DEGREE HRM_EMPLOYEE_DEGREE2 { get; set; }
    }
}
