//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_EMPLOYEE_ACCIDENT
    {
        public int VictimID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Status { get; set; }
        public int AccidentID { get; set; }
    
        public virtual DIC_ACCIDENT DIC_ACCIDENT { get; set; }
        public virtual HRM_EMPLOYEE HRM_EMPLOYEE { get; set; }
    }
}
