//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_ATTLOG
    {
        public int AttLogID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> MachineID { get; set; }
    
        public virtual DIC_MACHINE DIC_MACHINE { get; set; }
        public virtual HRM_EMPLOYEE HRM_EMPLOYEE { get; set; }
    }
}
