//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_CLOTHING_TIMELINE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HRM_CLOTHING_TIMELINE()
        {
            this.HRM_CLOTHING_DETAILS = new HashSet<HRM_CLOTHING_DETAILS>();
        }
    
        public int ClothingTimelineID { get; set; }
        public System.DateTime DeliverDate { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRM_CLOTHING_DETAILS> HRM_CLOTHING_DETAILS { get; set; }
    }
}
