//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_TIMEKEEPER
    {
        public int TimeKeeperID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime Date { get; set; }
        public int ShiftID { get; set; }
        public Nullable<int> SymbolID { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public Nullable<int> MachineID_In { get; set; }
        public Nullable<int> MachineID_Out { get; set; }
        public string Description { get; set; }
    
        public virtual DIC_MACHINE DIC_MACHINE { get; set; }
        public virtual DIC_MACHINE DIC_MACHINE1 { get; set; }
        public virtual DIC_SHIFT DIC_SHIFT { get; set; }
        public virtual DIC_SYMBOL DIC_SYMBOL { get; set; }
        public virtual HRM_EMPLOYEE HRM_EMPLOYEE { get; set; }
    }
}
