//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_EMPLOYEE_RETRIBUTION
    {
        public int EmployeeRetributionID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> TypeOfRetributionID { get; set; }
        public Nullable<int> RetributionNo { get; set; }
        public Nullable<System.DateTime> RetributionDate { get; set; }
        public string Reason { get; set; }
        public Nullable<int> EmploymentHistoryID { get; set; }
    
        public virtual DIC_TYPE_OF_RETRIBUTION DIC_TYPE_OF_RETRIBUTION { get; set; }
        public virtual HRM_EMPLOYEE HRM_EMPLOYEE { get; set; }
    }
}
