//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_CLOTHING_DETAILS
    {
        public int ClothingDetailsID { get; set; }
        public int ClothingID { get; set; }
        public int EmployeeID { get; set; }
        public int ClothingTimelineID { get; set; }
        public string Size { get; set; }
        public int Quantity { get; set; }
        public string Description { get; set; }
    
        public virtual DIC_CLOTHING DIC_CLOTHING { get; set; }
        public virtual HRM_CLOTHING_TIMELINE HRM_CLOTHING_TIMELINE { get; set; }
        public virtual HRM_EMPLOYEE HRM_EMPLOYEE { get; set; }
    }
}
