//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_EMPLOYEE_RELATIVE
    {
        public int PersonID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string PersonName { get; set; }
        public Nullable<int> RelativeID { get; set; }
        public string Birthday { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string IncomeTaxCode { get; set; }
        public string Job { get; set; }
        public string CompanyAddress { get; set; }
    
        public virtual DIC_RELATIVE DIC_RELATIVE { get; set; }
        public virtual HRM_EMPLOYEE HRM_EMPLOYEE { get; set; }
    }
}
