//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_DETAILSALARY
    {
        public int HRMDetailSalaryID { get; set; }
        public int HRMSalaryID { get; set; }
        public int EmployeeID { get; set; }
        public int EmploymentHistoryID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public string Position { get; set; }
        public Nullable<double> Salary { get; set; }
        public Nullable<double> AllowanceSalary { get; set; }
        public Nullable<double> Bonus { get; set; }
        public Nullable<double> AllowanceBonus { get; set; }
        public Nullable<int> NumOfDay { get; set; }
        public Nullable<double> TruKhac { get; set; }
        public Nullable<int> PhuThuoc { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> DepartmentSalaryID { get; set; }
        public Nullable<double> ThuLao { get; set; }
        public Nullable<double> Thuong { get; set; }
        public Nullable<double> ThuNhapTinhThueTNCN { get; set; }
        public Nullable<double> GiamTruCaNhan { get; set; }
        public Nullable<bool> IsBHXH { get; set; }
        public Nullable<bool> IsBHYT { get; set; }
        public Nullable<bool> IsCongDoan { get; set; }
        public Nullable<bool> IsBHTN { get; set; }
        public Nullable<bool> IsGiamTruCaNhan { get; set; }
        public string CongThuc { get; set; }
    }
}
