//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_EMPLOYEE_DISCIPLINE
    {
        public int EmployeeDisciplineID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> TypeOfDisciplineID { get; set; }
        public Nullable<int> DisciplineNo { get; set; }
        public Nullable<System.DateTime> DisciplineDate { get; set; }
        public string Reason { get; set; }
        public Nullable<int> EmploymentHistoryID { get; set; }
        public Nullable<System.DateTime> NgayHopHoiDong { get; set; }
        public string HinhThucKyLuat { get; set; }
        public Nullable<bool> CatThuong { get; set; }
    
        public virtual DIC_TYPE_OF_DISCIPLINE DIC_TYPE_OF_DISCIPLINE { get; set; }
        public virtual HRM_EMPLOYEE HRM_EMPLOYEE { get; set; }
    }
}
