//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AuLacEntities : DbContext
    {
        public AuLacEntities()
            : base("name=AuLacEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<ChungChiTau> ChungChiTaus { get; set; }
        public virtual DbSet<DIC_ACCIDENT> DIC_ACCIDENT { get; set; }
        public virtual DbSet<DIC_ALLOWANCE> DIC_ALLOWANCE { get; set; }
        public virtual DbSet<DIC_CATEGORYDECISION> DIC_CATEGORYDECISION { get; set; }
        public virtual DbSet<DIC_CLOTHING> DIC_CLOTHING { get; set; }
        public virtual DbSet<DIC_CONTRACTTYPE> DIC_CONTRACTTYPE { get; set; }
        public virtual DbSet<DIC_DEGREE> DIC_DEGREE { get; set; }
        public virtual DbSet<DIC_DEPARTMENT> DIC_DEPARTMENT { get; set; }
        public virtual DbSet<DIC_DEPARTMENT_POSITION> DIC_DEPARTMENT_POSITION { get; set; }
        public virtual DbSet<DIC_EDUCATION> DIC_EDUCATION { get; set; }
        public virtual DbSet<DIC_ETHNIC> DIC_ETHNIC { get; set; }
        public virtual DbSet<DIC_GROUPCONTRACTTYPE> DIC_GROUPCONTRACTTYPE { get; set; }
        public virtual DbSet<DIC_GROUPPOSITION> DIC_GROUPPOSITION { get; set; }
        public virtual DbSet<DIC_HOSPITAL> DIC_HOSPITAL { get; set; }
        public virtual DbSet<DIC_INFORMATIC> DIC_INFORMATIC { get; set; }
        public virtual DbSet<DIC_INTERSHIP> DIC_INTERSHIP { get; set; }
        public virtual DbSet<DIC_JOB> DIC_JOB { get; set; }
        public virtual DbSet<DIC_KHUVUC> DIC_KHUVUC { get; set; }
        public virtual DbSet<DIC_LANGUAGE> DIC_LANGUAGE { get; set; }
        public virtual DbSet<DIC_LOAITAU> DIC_LOAITAU { get; set; }
        public virtual DbSet<DIC_MACHINE> DIC_MACHINE { get; set; }
        public virtual DbSet<DIC_NATIONALITY> DIC_NATIONALITY { get; set; }
        public virtual DbSet<DIC_PHUONGXA> DIC_PHUONGXA { get; set; }
        public virtual DbSet<DIC_POSITION> DIC_POSITION { get; set; }
        public virtual DbSet<DIC_POSITION_DEGREE> DIC_POSITION_DEGREE { get; set; }
        public virtual DbSet<DIC_PROFESSIONAL> DIC_PROFESSIONAL { get; set; }
        public virtual DbSet<DIC_PROVINCE> DIC_PROVINCE { get; set; }
        public virtual DbSet<DIC_QUANHUYEN> DIC_QUANHUYEN { get; set; }
        public virtual DbSet<DIC_RANK> DIC_RANK { get; set; }
        public virtual DbSet<DIC_RELATIVE> DIC_RELATIVE { get; set; }
        public virtual DbSet<DIC_RELIGION> DIC_RELIGION { get; set; }
        public virtual DbSet<DIC_SALARY> DIC_SALARY { get; set; }
        public virtual DbSet<DIC_SALARY_DEPARTMENT> DIC_SALARY_DEPARTMENT { get; set; }
        public virtual DbSet<DIC_SALARY_STEP> DIC_SALARY_STEP { get; set; }
        public virtual DbSet<DIC_SCHOOL> DIC_SCHOOL { get; set; }
        public virtual DbSet<DIC_SHIFT> DIC_SHIFT { get; set; }
        public virtual DbSet<DIC_SKILL> DIC_SKILL { get; set; }
        public virtual DbSet<DIC_STATUS> DIC_STATUS { get; set; }
        public virtual DbSet<DIC_SYMBOL> DIC_SYMBOL { get; set; }
        public virtual DbSet<DIC_TINHTHANHPHO> DIC_TINHTHANHPHO { get; set; }
        public virtual DbSet<DIC_TYPE_OF_DISCIPLINE> DIC_TYPE_OF_DISCIPLINE { get; set; }
        public virtual DbSet<DIC_TYPE_OF_RETRIBUTION> DIC_TYPE_OF_RETRIBUTION { get; set; }
        public virtual DbSet<DieuDongBacThang> DieuDongBacThangs { get; set; }
        public virtual DbSet<HeDaoTao> HeDaoTaos { get; set; }
        public virtual DbSet<HoSoCongTy> HoSoCongTies { get; set; }
        public virtual DbSet<HoSoTau> HoSoTaus { get; set; }
        public virtual DbSet<HRM_ACCIDENT> HRM_ACCIDENT { get; set; }
        public virtual DbSet<HRM_ATTLOG> HRM_ATTLOG { get; set; }
        public virtual DbSet<HRM_CLOTHING_DETAILS> HRM_CLOTHING_DETAILS { get; set; }
        public virtual DbSet<HRM_CLOTHING_TIMELINE> HRM_CLOTHING_TIMELINE { get; set; }
        public virtual DbSet<HRM_CONTRACTHISTORY> HRM_CONTRACTHISTORY { get; set; }
        public virtual DbSet<HRM_DEPARTMENT> HRM_DEPARTMENT { get; set; }
        public virtual DbSet<HRM_DETAILPLAN> HRM_DETAILPLAN { get; set; }
        public virtual DbSet<HRM_DETAILSALARY> HRM_DETAILSALARY { get; set; }
        public virtual DbSet<HRM_EMPLOYEE> HRM_EMPLOYEE { get; set; }
        public virtual DbSet<HRM_EMPLOYEE_ACCIDENT> HRM_EMPLOYEE_ACCIDENT { get; set; }
        public virtual DbSet<HRM_EMPLOYEE_CLOTHING> HRM_EMPLOYEE_CLOTHING { get; set; }
        public virtual DbSet<HRM_EMPLOYEE_DEGREE> HRM_EMPLOYEE_DEGREE { get; set; }
        public virtual DbSet<HRM_EMPLOYEE_DISCIPLINE> HRM_EMPLOYEE_DISCIPLINE { get; set; }
        public virtual DbSet<HRM_EMPLOYEE_RELATIVE> HRM_EMPLOYEE_RELATIVE { get; set; }
        public virtual DbSet<HRM_EMPLOYEE_RETRIBUTION> HRM_EMPLOYEE_RETRIBUTION { get; set; }
        public virtual DbSet<HRM_EMPLOYEE_SCHEDULE> HRM_EMPLOYEE_SCHEDULE { get; set; }
        public virtual DbSet<HRM_EMPLOYMENTHISTORY> HRM_EMPLOYMENTHISTORY { get; set; }
        public virtual DbSet<HRM_PLAN> HRM_PLAN { get; set; }
        public virtual DbSet<HRM_QTCT> HRM_QTCT { get; set; }
        public virtual DbSet<HRM_ROLE> HRM_ROLE { get; set; }
        public virtual DbSet<HRM_SALARY> HRM_SALARY { get; set; }
        public virtual DbSet<HRM_SALARYMONTH> HRM_SALARYMONTH { get; set; }
        public virtual DbSet<HRM_TIMEKEEPER> HRM_TIMEKEEPER { get; set; }
        public virtual DbSet<HRM_TIMEKEEPER_TABLELIST> HRM_TIMEKEEPER_TABLELIST { get; set; }
        public virtual DbSet<HRM_USER> HRM_USER { get; set; }
        public virtual DbSet<HRM_USERROLES> HRM_USERROLES { get; set; }
        public virtual DbSet<LichKiemTra> LichKiemTras { get; set; }
        public virtual DbSet<LoaiKiemTra> LoaiKiemTras { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_cosodaotao> tbl_cosodaotao { get; set; }
        public virtual DbSet<tbl_ctdaotao> tbl_ctdaotao { get; set; }
        public virtual DbSet<tbl_khoadaotao> tbl_khoadaotao { get; set; }
        public virtual DbSet<tbl_LyDoNghiViec> tbl_LyDoNghiViec { get; set; }
        public virtual DbSet<tbl_QuanHe> tbl_QuanHe { get; set; }
        public virtual DbSet<tblLuongTam> tblLuongTams { get; set; }
        public virtual DbSet<TieuChuanCrewMatrix> TieuChuanCrewMatrices { get; set; }
        public virtual DbSet<TrinhDoAnhVan> TrinhDoAnhVans { get; set; }
        public virtual DbSet<TrinhDoViTinh> TrinhDoViTinhs { get; set; }
        public virtual DbSet<VideoFile> VideoFiles { get; set; }
        public virtual DbSet<SYS_COMPANY> SYS_COMPANY { get; set; }
        public virtual DbSet<view_EMPLOYMENTHISTORY_DauNam> view_EMPLOYMENTHISTORY_DauNam { get; set; }
        public virtual DbSet<view_FirstEMPLOYMENTHISTORY> view_FirstEMPLOYMENTHISTORY { get; set; }
        public virtual DbSet<view_HRM_PLAN> view_HRM_PLAN { get; set; }
        public virtual DbSet<view_NghiViec> view_NghiViec { get; set; }
        public virtual DbSet<view_qtct_goc> view_qtct_goc { get; set; }
        public virtual DbSet<view_quatrinhcongtac> view_quatrinhcongtac { get; set; }
        public virtual DbSet<view_quatrinhcongtacFull> view_quatrinhcongtacFull { get; set; }
        public virtual DbSet<viewHopDongGanNhat> viewHopDongGanNhats { get; set; }
        public virtual DbSet<viewHRM_EMPLOYMENTHISTORY> viewHRM_EMPLOYMENTHISTORY { get; set; }
        public virtual DbSet<viewLuongCoBan> viewLuongCoBans { get; set; }
        public virtual DbSet<viewLuongThang> viewLuongThangs { get; set; }
        public virtual DbSet<viewNhanVien> viewNhanViens { get; set; }
        public virtual DbSet<viewNhanVienTongHop> viewNhanVienTongHops { get; set; }
    
        [DbFunction("AuLacEntities", "fn_DegreeLimitList")]
        public virtual IQueryable<fn_DegreeLimitList_Result> fn_DegreeLimitList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_DegreeLimitList_Result>("[AuLacEntities].[fn_DegreeLimitList]()");
        }
    
        [DbFunction("AuLacEntities", "fn_DegreeLimitList_NhanVien")]
        public virtual IQueryable<fn_DegreeLimitList_NhanVien_Result> fn_DegreeLimitList_NhanVien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_DegreeLimitList_NhanVien_Result>("[AuLacEntities].[fn_DegreeLimitList_NhanVien]()");
        }
    
        [DbFunction("AuLacEntities", "fn_IsLimitDegree")]
        public virtual IQueryable<fn_IsLimitDegree_Result> fn_IsLimitDegree()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_IsLimitDegree_Result>("[AuLacEntities].[fn_IsLimitDegree]()");
        }
    
        [DbFunction("AuLacEntities", "fn_ListCrewTemp")]
        public virtual IQueryable<fn_ListCrewTemp_Result> fn_ListCrewTemp(Nullable<int> planID)
        {
            var planIDParameter = planID.HasValue ?
                new ObjectParameter("planID", planID) :
                new ObjectParameter("planID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_ListCrewTemp_Result>("[AuLacEntities].[fn_ListCrewTemp](@planID)", planIDParameter);
        }
    
        [DbFunction("AuLacEntities", "fn_TestDegree")]
        public virtual IQueryable<fn_TestDegree_Result> fn_TestDegree()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_TestDegree_Result>("[AuLacEntities].[fn_TestDegree]()");
        }
    
        [DbFunction("AuLacEntities", "fn_XacNhanQuyetDinh")]
        public virtual IQueryable<fn_XacNhanQuyetDinh_Result> fn_XacNhanQuyetDinh(Nullable<int> planID)
        {
            var planIDParameter = planID.HasValue ?
                new ObjectParameter("planID", planID) :
                new ObjectParameter("planID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_XacNhanQuyetDinh_Result>("[AuLacEntities].[fn_XacNhanQuyetDinh](@planID)", planIDParameter);
        }
    
        public virtual ObjectResult<sp_BangTheoDoiGiayToTau_Result> sp_BangTheoDoiGiayToTau(Nullable<System.DateTime> ngayBaoCao)
        {
            var ngayBaoCaoParameter = ngayBaoCao.HasValue ?
                new ObjectParameter("ngayBaoCao", ngayBaoCao) :
                new ObjectParameter("ngayBaoCao", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BangTheoDoiGiayToTau_Result>("sp_BangTheoDoiGiayToTau", ngayBaoCaoParameter);
        }
    
        public virtual ObjectResult<string> sp_GetYMD(Nullable<System.DateTime> date, Nullable<System.DateTime> date2)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var date2Parameter = date2.HasValue ?
                new ObjectParameter("date2", date2) :
                new ObjectParameter("date2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_GetYMD", dateParameter, date2Parameter);
        }
    
        public virtual int sp_InsertBangLuong(Nullable<int> hrmSalaryID)
        {
            var hrmSalaryIDParameter = hrmSalaryID.HasValue ?
                new ObjectParameter("hrmSalaryID", hrmSalaryID) :
                new ObjectParameter("hrmSalaryID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertBangLuong", hrmSalaryIDParameter);
        }
    
        public virtual int sp_InsertChiTietKeHoachDieuDong(Nullable<int> planID, Nullable<int> departmentID, Nullable<int> crewOffID, Nullable<int> crewOnID)
        {
            var planIDParameter = planID.HasValue ?
                new ObjectParameter("planID", planID) :
                new ObjectParameter("planID", typeof(int));
    
            var departmentIDParameter = departmentID.HasValue ?
                new ObjectParameter("departmentID", departmentID) :
                new ObjectParameter("departmentID", typeof(int));
    
            var crewOffIDParameter = crewOffID.HasValue ?
                new ObjectParameter("crewOffID", crewOffID) :
                new ObjectParameter("crewOffID", typeof(int));
    
            var crewOnIDParameter = crewOnID.HasValue ?
                new ObjectParameter("crewOnID", crewOnID) :
                new ObjectParameter("crewOnID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertChiTietKeHoachDieuDong", planIDParameter, departmentIDParameter, crewOffIDParameter, crewOnIDParameter);
        }
    
        public virtual ObjectResult<sp_LayDSBangCapTheoChucVu_Result> sp_LayDSBangCapTheoChucVu(Nullable<int> employeeID, Nullable<int> positionID, Nullable<System.DateTime> ngayBaoCao)
        {
            var employeeIDParameter = employeeID.HasValue ?
                new ObjectParameter("employeeID", employeeID) :
                new ObjectParameter("employeeID", typeof(int));
    
            var positionIDParameter = positionID.HasValue ?
                new ObjectParameter("positionID", positionID) :
                new ObjectParameter("positionID", typeof(int));
    
            var ngayBaoCaoParameter = ngayBaoCao.HasValue ?
                new ObjectParameter("NgayBaoCao", ngayBaoCao) :
                new ObjectParameter("NgayBaoCao", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayDSBangCapTheoChucVu_Result>("sp_LayDSBangCapTheoChucVu", employeeIDParameter, positionIDParameter, ngayBaoCaoParameter);
        }
    
        public virtual ObjectResult<sp_LayDSBangCapTheoID_Result> sp_LayDSBangCapTheoID(Nullable<int> bcID)
        {
            var bcIDParameter = bcID.HasValue ?
                new ObjectParameter("bcID", bcID) :
                new ObjectParameter("bcID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayDSBangCapTheoID_Result>("sp_LayDSBangCapTheoID", bcIDParameter);
        }
    
        public virtual ObjectResult<sp_LayDSBoNhiem_Result> sp_LayDSBoNhiem(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayDSBoNhiem_Result>("sp_LayDSBoNhiem", tungayParameter, denngayParameter);
        }
    
        public virtual ObjectResult<sp_LayDSChungChiHetHanTheoSoThang_Result> sp_LayDSChungChiHetHanTheoSoThang(Nullable<int> sothang, Nullable<int> loaiNV)
        {
            var sothangParameter = sothang.HasValue ?
                new ObjectParameter("sothang", sothang) :
                new ObjectParameter("sothang", typeof(int));
    
            var loaiNVParameter = loaiNV.HasValue ?
                new ObjectParameter("loaiNV", loaiNV) :
                new ObjectParameter("loaiNV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayDSChungChiHetHanTheoSoThang_Result>("sp_LayDSChungChiHetHanTheoSoThang", sothangParameter, loaiNVParameter);
        }
    
        public virtual ObjectResult<sp_LayDSChungChiTau_Result> sp_LayDSChungChiTau()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayDSChungChiTau_Result>("sp_LayDSChungChiTau");
        }
    
        public virtual ObjectResult<sp_LayDSDuTru_Result> sp_LayDSDuTru(Nullable<int> planID, Nullable<int> departmentID)
        {
            var planIDParameter = planID.HasValue ?
                new ObjectParameter("planID", planID) :
                new ObjectParameter("planID", typeof(int));
    
            var departmentIDParameter = departmentID.HasValue ?
                new ObjectParameter("departmentID", departmentID) :
                new ObjectParameter("departmentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayDSDuTru_Result>("sp_LayDSDuTru", planIDParameter, departmentIDParameter);
        }
    
        public virtual ObjectResult<sp_LayDSDuTruTheoKeHoach_Result> sp_LayDSDuTruTheoKeHoach(Nullable<int> planID, Nullable<int> departmentID, Nullable<int> crewOffID)
        {
            var planIDParameter = planID.HasValue ?
                new ObjectParameter("planID", planID) :
                new ObjectParameter("planID", typeof(int));
    
            var departmentIDParameter = departmentID.HasValue ?
                new ObjectParameter("departmentID", departmentID) :
                new ObjectParameter("departmentID", typeof(int));
    
            var crewOffIDParameter = crewOffID.HasValue ?
                new ObjectParameter("crewOffID", crewOffID) :
                new ObjectParameter("crewOffID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayDSDuTruTheoKeHoach_Result>("sp_LayDSDuTruTheoKeHoach", planIDParameter, departmentIDParameter, crewOffIDParameter);
        }
    
        public virtual ObjectResult<sp_LayDSKhongDatHopDong_Result> sp_LayDSKhongDatHopDong()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayDSKhongDatHopDong_Result>("sp_LayDSKhongDatHopDong");
        }
    
        public virtual ObjectResult<sp_LayDSKhongDatPassport_Result> sp_LayDSKhongDatPassport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayDSKhongDatPassport_Result>("sp_LayDSKhongDatPassport");
        }
    
        public virtual ObjectResult<sp_LayDSKyLuat_Result> sp_LayDSKyLuat(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayDSKyLuat_Result>("sp_LayDSKyLuat", tungayParameter, denngayParameter);
        }
    
        public virtual ObjectResult<sp_LayDSNghiViec_Result> sp_LayDSNghiViec(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, Nullable<int> loainv)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var loainvParameter = loainv.HasValue ?
                new ObjectParameter("loainv", loainv) :
                new ObjectParameter("loainv", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayDSNghiViec_Result>("sp_LayDSNghiViec", tungayParameter, denngayParameter, loainvParameter);
        }
    
        public virtual ObjectResult<sp_LayDSNhanVienTheoNgay_Result> sp_LayDSNhanVienTheoNgay(Nullable<System.DateTime> ngay)
        {
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayDSNhanVienTheoNgay_Result>("sp_LayDSNhanVienTheoNgay", ngayParameter);
        }
    
        public virtual ObjectResult<sp_LayDSThanNhan_Result> sp_LayDSThanNhan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayDSThanNhan_Result>("sp_LayDSThanNhan");
        }
    
        public virtual ObjectResult<sp_LayDSThuyenVien_Result> sp_LayDSThuyenVien(Nullable<int> planID)
        {
            var planIDParameter = planID.HasValue ?
                new ObjectParameter("planID", planID) :
                new ObjectParameter("planID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayDSThuyenVien_Result>("sp_LayDSThuyenVien", planIDParameter);
        }
    
        public virtual ObjectResult<sp_LayDSThuyenVienDieuDong_Result> sp_LayDSThuyenVienDieuDong(Nullable<int> planID)
        {
            var planIDParameter = planID.HasValue ?
                new ObjectParameter("planID", planID) :
                new ObjectParameter("planID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayDSThuyenVienDieuDong_Result>("sp_LayDSThuyenVienDieuDong", planIDParameter);
        }
    
        public virtual ObjectResult<sp_LayDSThuyenVienHuyTuyenDung_Result> sp_LayDSThuyenVienHuyTuyenDung(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayDSThuyenVienHuyTuyenDung_Result>("sp_LayDSThuyenVienHuyTuyenDung", tungayParameter, denngayParameter);
        }
    
        public virtual ObjectResult<sp_LayDSThuyenVienTheoLoaiChucDanh_Result> sp_LayDSThuyenVienTheoLoaiChucDanh(Nullable<int> loaiChucDanh)
        {
            var loaiChucDanhParameter = loaiChucDanh.HasValue ?
                new ObjectParameter("loaiChucDanh", loaiChucDanh) :
                new ObjectParameter("loaiChucDanh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayDSThuyenVienTheoLoaiChucDanh_Result>("sp_LayDSThuyenVienTheoLoaiChucDanh", loaiChucDanhParameter);
        }
    
        public virtual ObjectResult<sp_LayDSThuyenVienTheoLoaiQuyetDinh_Result> sp_LayDSThuyenVienTheoLoaiQuyetDinh(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, Nullable<int> loaiQD)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var loaiQDParameter = loaiQD.HasValue ?
                new ObjectParameter("loaiQD", loaiQD) :
                new ObjectParameter("loaiQD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayDSThuyenVienTheoLoaiQuyetDinh_Result>("sp_LayDSThuyenVienTheoLoaiQuyetDinh", tungayParameter, denngayParameter, loaiQDParameter);
        }
    
        public virtual ObjectResult<sp_LayDSTuyenDung_Result> sp_LayDSTuyenDung(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, Nullable<int> loainv)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var loainvParameter = loainv.HasValue ?
                new ObjectParameter("loainv", loainv) :
                new ObjectParameter("loainv", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayDSTuyenDung_Result>("sp_LayDSTuyenDung", tungayParameter, denngayParameter, loainvParameter);
        }
    
        public virtual ObjectResult<sp_LayKeHoachDieuDong_Result> sp_LayKeHoachDieuDong(Nullable<int> planID)
        {
            var planIDParameter = planID.HasValue ?
                new ObjectParameter("planID", planID) :
                new ObjectParameter("planID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayKeHoachDieuDong_Result>("sp_LayKeHoachDieuDong", planIDParameter);
        }
    
        public virtual int sp_LayLuongThang(Nullable<int> hrmSalaryID, Nullable<int> depart)
        {
            var hrmSalaryIDParameter = hrmSalaryID.HasValue ?
                new ObjectParameter("hrmSalaryID", hrmSalaryID) :
                new ObjectParameter("hrmSalaryID", typeof(int));
    
            var departParameter = depart.HasValue ?
                new ObjectParameter("depart", depart) :
                new ObjectParameter("depart", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LayLuongThang", hrmSalaryIDParameter, departParameter);
        }
    
        public virtual ObjectResult<sp_LayThongTinMatrix_Result> sp_LayThongTinMatrix(Nullable<int> chucDanhID, Nullable<int> employeeID)
        {
            var chucDanhIDParameter = chucDanhID.HasValue ?
                new ObjectParameter("chucDanhID", chucDanhID) :
                new ObjectParameter("chucDanhID", typeof(int));
    
            var employeeIDParameter = employeeID.HasValue ?
                new ObjectParameter("employeeID", employeeID) :
                new ObjectParameter("employeeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayThongTinMatrix_Result>("sp_LayThongTinMatrix", chucDanhIDParameter, employeeIDParameter);
        }
    
        public virtual int sp_LayTienLuong(Nullable<int> hrmSalaryID)
        {
            var hrmSalaryIDParameter = hrmSalaryID.HasValue ?
                new ObjectParameter("hrmSalaryID", hrmSalaryID) :
                new ObjectParameter("hrmSalaryID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LayTienLuong", hrmSalaryIDParameter);
        }
    
        public virtual int sp_Luong_1(Nullable<int> hrmSalaryID)
        {
            var hrmSalaryIDParameter = hrmSalaryID.HasValue ?
                new ObjectParameter("hrmSalaryID", hrmSalaryID) :
                new ObjectParameter("hrmSalaryID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Luong_1", hrmSalaryIDParameter);
        }
    
        public virtual ObjectResult<sp_Luong_3_Result> sp_Luong_3(Nullable<int> hrmSalaryID)
        {
            var hrmSalaryIDParameter = hrmSalaryID.HasValue ?
                new ObjectParameter("hrmSalaryID", hrmSalaryID) :
                new ObjectParameter("hrmSalaryID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Luong_3_Result>("sp_Luong_3", hrmSalaryIDParameter);
        }
    
        public virtual ObjectResult<sp_T_CrewMatrixTau_Result> sp_T_CrewMatrixTau(Nullable<int> idTau, Nullable<int> idPlan, Nullable<int> idOn, Nullable<int> idOff, Nullable<int> tieuChuan)
        {
            var idTauParameter = idTau.HasValue ?
                new ObjectParameter("idTau", idTau) :
                new ObjectParameter("idTau", typeof(int));
    
            var idPlanParameter = idPlan.HasValue ?
                new ObjectParameter("idPlan", idPlan) :
                new ObjectParameter("idPlan", typeof(int));
    
            var idOnParameter = idOn.HasValue ?
                new ObjectParameter("idOn", idOn) :
                new ObjectParameter("idOn", typeof(int));
    
            var idOffParameter = idOff.HasValue ?
                new ObjectParameter("idOff", idOff) :
                new ObjectParameter("idOff", typeof(int));
    
            var tieuChuanParameter = tieuChuan.HasValue ?
                new ObjectParameter("tieuChuan", tieuChuan) :
                new ObjectParameter("tieuChuan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_T_CrewMatrixTau_Result>("sp_T_CrewMatrixTau", idTauParameter, idPlanParameter, idOnParameter, idOffParameter, tieuChuanParameter);
        }
    
        public virtual ObjectResult<sp_T_LayDanhSachHocTheoThoiGian_Result> sp_T_LayDanhSachHocTheoThoiGian(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("tuNgay", tuNgay) :
                new ObjectParameter("tuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("denNgay", denNgay) :
                new ObjectParameter("denNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_T_LayDanhSachHocTheoThoiGian_Result>("sp_T_LayDanhSachHocTheoThoiGian", tuNgayParameter, denNgayParameter);
        }
    
        public virtual ObjectResult<sp_T_LayDanhSachNhanVien_Result> sp_T_LayDanhSachNhanVien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_T_LayDanhSachNhanVien_Result>("sp_T_LayDanhSachNhanVien");
        }
    
        public virtual ObjectResult<sp_T_LayDieuDongBacThangTheoChucDanh_Result> sp_T_LayDieuDongBacThangTheoChucDanh(Nullable<int> posID, Nullable<System.DateTime> ngayTinh, string posName)
        {
            var posIDParameter = posID.HasValue ?
                new ObjectParameter("posID", posID) :
                new ObjectParameter("posID", typeof(int));
    
            var ngayTinhParameter = ngayTinh.HasValue ?
                new ObjectParameter("ngayTinh", ngayTinh) :
                new ObjectParameter("ngayTinh", typeof(System.DateTime));
    
            var posNameParameter = posName != null ?
                new ObjectParameter("posName", posName) :
                new ObjectParameter("posName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_T_LayDieuDongBacThangTheoChucDanh_Result>("sp_T_LayDieuDongBacThangTheoChucDanh", posIDParameter, ngayTinhParameter, posNameParameter);
        }
    
        public virtual ObjectResult<sp_T_LayLichTauTrongDieuDongBacThang_Result> sp_T_LayLichTauTrongDieuDongBacThang(Nullable<System.DateTime> ngayTinh)
        {
            var ngayTinhParameter = ngayTinh.HasValue ?
                new ObjectParameter("ngayTinh", ngayTinh) :
                new ObjectParameter("ngayTinh", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_T_LayLichTauTrongDieuDongBacThang_Result>("sp_T_LayLichTauTrongDieuDongBacThang", ngayTinhParameter);
        }
    
        public virtual ObjectResult<sp_T_LayNguoiThayThe_Result> sp_T_LayNguoiThayThe(Nullable<int> nguoiThayTheID, Nullable<int> posID)
        {
            var nguoiThayTheIDParameter = nguoiThayTheID.HasValue ?
                new ObjectParameter("NguoiThayTheID", nguoiThayTheID) :
                new ObjectParameter("NguoiThayTheID", typeof(int));
    
            var posIDParameter = posID.HasValue ?
                new ObjectParameter("posID", posID) :
                new ObjectParameter("posID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_T_LayNguoiThayThe_Result>("sp_T_LayNguoiThayThe", nguoiThayTheIDParameter, posIDParameter);
        }
    
        public virtual int sp_T_TaoDuLieuBanDauChoDieuDong()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_T_TaoDuLieuBanDauChoDieuDong");
        }
    
        public virtual ObjectResult<string> sp_T_TaoMaNhanVien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_T_TaoMaNhanVien");
        }
    
        public virtual ObjectResult<sp_T_ThongKeDaoTaoCaNhan_Result> sp_T_ThongKeDaoTaoCaNhan(Nullable<int> employeeID)
        {
            var employeeIDParameter = employeeID.HasValue ?
                new ObjectParameter("employeeID", employeeID) :
                new ObjectParameter("employeeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_T_ThongKeDaoTaoCaNhan_Result>("sp_T_ThongKeDaoTaoCaNhan", employeeIDParameter);
        }
    
        public virtual int sp_T_UpdateSTTLenXuong(Nullable<int> id, Nullable<int> isLen)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var isLenParameter = isLen.HasValue ?
                new ObjectParameter("isLen", isLen) :
                new ObjectParameter("isLen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_T_UpdateSTTLenXuong", idParameter, isLenParameter);
        }
    
        public virtual int sp_T_UpdateSTTLenXuong_ChungChiTau(Nullable<int> id, Nullable<int> isLen)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var isLenParameter = isLen.HasValue ?
                new ObjectParameter("isLen", isLen) :
                new ObjectParameter("isLen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_T_UpdateSTTLenXuong_ChungChiTau", idParameter, isLenParameter);
        }
    
        public virtual ObjectResult<sp_ThoiGianLamViecTaiCongTy_Result> sp_ThoiGianLamViecTaiCongTy(Nullable<int> employeeID)
        {
            var employeeIDParameter = employeeID.HasValue ?
                new ObjectParameter("employeeID", employeeID) :
                new ObjectParameter("employeeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThoiGianLamViecTaiCongTy_Result>("sp_ThoiGianLamViecTaiCongTy", employeeIDParameter);
        }
    }
}
