//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_COMPANY
    {
        public string Company_Id { get; set; }
        public string CompanyCode { get; set; }
        public string Company { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string WebSite { get; set; }
        public string Email { get; set; }
        public string Tax { get; set; }
        public string Licence { get; set; }
        public byte[] Photo { get; set; }
        public string BankAccount { get; set; }
        public string OpenedAt { get; set; }
        public string BankAbbreviationName { get; set; }
        public string BankBranch { get; set; }
    }
}
