//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LyDoNghiViec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_LyDoNghiViec()
        {
            this.HRM_EMPLOYMENTHISTORY = new HashSet<HRM_EMPLOYMENTHISTORY>();
            this.HRM_QTCT = new HashSet<HRM_QTCT>();
        }
    
        public int LyDoNghiViec_ID { get; set; }
        public string LyDoNghiViec_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRM_EMPLOYMENTHISTORY> HRM_EMPLOYMENTHISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRM_QTCT> HRM_QTCT { get; set; }
    }
}
