//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_khoadaotao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_khoadaotao()
        {
            this.tbl_ctdaotao = new HashSet<tbl_ctdaotao>();
        }
    
        public int id_khoadaotao { get; set; }
        public Nullable<int> id_cosodaotao { get; set; }
        public string tenkhoadaotao { get; set; }
        public Nullable<System.DateTime> ngaybatdau { get; set; }
        public Nullable<decimal> hocphi { get; set; }
        public string diadiem { get; set; }
        public string MonHoc { get; set; }
        public string CapDo { get; set; }
        public string GiayChungNhan { get; set; }
        public string TheoYeuCau { get; set; }
        public string KhoaDaoTao { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
    
        public virtual tbl_cosodaotao tbl_cosodaotao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ctdaotao> tbl_ctdaotao { get; set; }
    }
}
