//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ctdaotao
    {
        public int id_ctdaotao { get; set; }
        public Nullable<int> id_khoadaotao { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string ketqua { get; set; }
        public string GhiChu { get; set; }
        public string ChucVu { get; set; }
    
        public virtual HRM_EMPLOYEE HRM_EMPLOYEE { get; set; }
        public virtual tbl_khoadaotao tbl_khoadaotao { get; set; }
    }
}
