//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLuongTam
    {
        public int HRMSalaryID { get; set; }
        public int HRMDetailSalaryID { get; set; }
        public int EmployeeID { get; set; }
        public int EmploymentHistoryID { get; set; }
        public Nullable<int> EmploymentHistoryIDLuong { get; set; }
    }
}
