//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TieuChuanCrewMatrix
    {
        public int TieuChuanID { get; set; }
        public string TieuChuanName { get; set; }
        public Nullable<decimal> WithOperator_QuanLyBoong { get; set; }
        public Nullable<decimal> InRank_QuanLyBoong { get; set; }
        public Nullable<decimal> ThisTypeOfTanker_QuanLyBoong { get; set; }
        public Nullable<decimal> AllTypeOfTanker_QuanLyBoong { get; set; }
        public Nullable<decimal> WithOperator_ThuyenTruong { get; set; }
        public Nullable<decimal> InRank_ThuyenTruong { get; set; }
        public Nullable<decimal> ThisTypeOfTanker_ThuyenTruong { get; set; }
        public Nullable<decimal> AllTypeOfTanker_ThuyenTruong { get; set; }
        public Nullable<decimal> WithOperator_DaiPho { get; set; }
        public Nullable<decimal> InRank_DaiPho { get; set; }
        public Nullable<decimal> ThisTypeOfTanker_DaiPho { get; set; }
        public Nullable<decimal> AllTypeOfTanker_DaiPho { get; set; }
        public Nullable<decimal> WithOperator_QuanLyMay { get; set; }
        public Nullable<decimal> InRank_QuanLyMay { get; set; }
        public Nullable<decimal> ThisTypeOfTanker_QuanLyMay { get; set; }
        public Nullable<decimal> AllTypeOfTanker_QuanLyMay { get; set; }
        public Nullable<decimal> WithOperator_MayTruong { get; set; }
        public Nullable<decimal> InRank_MayTruong { get; set; }
        public Nullable<decimal> ThisTypeOfTanker_MayTruong { get; set; }
        public Nullable<decimal> AllTypeOfTanker_MayTruong { get; set; }
        public Nullable<decimal> WithOperator_May2 { get; set; }
        public Nullable<decimal> InRank_May2 { get; set; }
        public Nullable<decimal> ThisTypeOfTanker_May2 { get; set; }
        public Nullable<decimal> AllTypeOfTanker_May2 { get; set; }
        public Nullable<decimal> WithOperator_VanHanhBoong { get; set; }
        public Nullable<decimal> InRank_VanHanhBoong { get; set; }
        public Nullable<decimal> ThisTypeOfTanker_VanHanhBoong { get; set; }
        public Nullable<decimal> AllTypeOfTanker_VanHanhBoong { get; set; }
        public Nullable<decimal> WithOperator_VanHanhMay { get; set; }
        public Nullable<decimal> InRank_VanHanhMay { get; set; }
        public Nullable<decimal> ThisTypeTanker_VanHanhMay { get; set; }
        public Nullable<decimal> AllTypeOfTanker_VanHanhMay { get; set; }
    }
}
