//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_NghiViec
    {
        public int EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int EmploymentHistoryID { get; set; }
        public Nullable<int> DecisionNo { get; set; }
        public Nullable<System.DateTime> DecisionDate { get; set; }
        public string Note { get; set; }
        public int PositionID { get; set; }
        public string PositionName { get; set; }
        public Nullable<int> GroupPositionID { get; set; }
        public Nullable<int> EducationID { get; set; }
        public string EducationName { get; set; }
        public string Description { get; set; }
        public string Qualification { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string EmployeeCode { get; set; }
        public Nullable<int> ContractHistoryID { get; set; }
        public Nullable<int> ContractTypeID { get; set; }
        public string ContractNo { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public string ContractTypeName { get; set; }
        public Nullable<int> GroupContractTypeID { get; set; }
        public string GroupContractTypeName { get; set; }
        public int DepartmentID { get; set; }
        public string DepartmentName { get; set; }
    }
}
