//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewLuongCoBan
    {
        public int EmployeeID { get; set; }
        public string EmployeeCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> ThuTuPhongBan { get; set; }
        public Nullable<int> ThuTuChucVu { get; set; }
        public Nullable<System.DateTime> NgayXuongTau { get; set; }
        public Nullable<double> TruKhac { get; set; }
        public Nullable<int> PhuThuoc { get; set; }
        public string GhiChu { get; set; }
        public Nullable<double> ThuLao { get; set; }
        public Nullable<double> Thuong { get; set; }
        public Nullable<double> GiamTruCaNhan { get; set; }
        public Nullable<bool> IsBHXH { get; set; }
        public Nullable<bool> IsBHYT { get; set; }
        public Nullable<bool> IsCongDoan { get; set; }
        public Nullable<bool> IsBHTN { get; set; }
        public Nullable<int> NumOfDay { get; set; }
        public string HRMSalaryName { get; set; }
        public Nullable<int> Years { get; set; }
        public Nullable<int> Months { get; set; }
        public Nullable<double> PerBHXH { get; set; }
        public Nullable<double> PerBHYT { get; set; }
        public Nullable<double> PerBHTN { get; set; }
        public Nullable<double> PerCongDoan { get; set; }
        public Nullable<int> TotalDay { get; set; }
        public Nullable<double> BHXH { get; set; }
        public Nullable<double> BHYT { get; set; }
        public Nullable<double> CongDoan { get; set; }
        public Nullable<double> BHTN { get; set; }
        public Nullable<double> TongThuNhap { get; set; }
        public Nullable<int> DepartmentLuongID { get; set; }
        public Nullable<bool> IsGiamTruCaNhan { get; set; }
        public int HRMDetailSalaryID { get; set; }
        public int HRMSalaryID { get; set; }
        public int EmploymentHistoryID { get; set; }
        public string BankCode { get; set; }
        public int DepartmentID { get; set; }
        public Nullable<int> PerPosition { get; set; }
        public Nullable<int> PerPlurality { get; set; }
        public double Salary { get; set; }
        public double AllowanceSalary { get; set; }
        public double Bonus { get; set; }
        public double AllowanceBonus { get; set; }
        public double SalaryPlurality { get; set; }
        public double AllowanceSalaryPlurality { get; set; }
        public double BonusPlurality { get; set; }
        public double AllowanceBonusPlurality { get; set; }
    }
}
