//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewNhanVien
    {
        public int EmployeeID { get; set; }
        public string EmployeeCode { get; set; }
        public string CardNo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Alias { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string BirthPlace { get; set; }
        public string MainAddress { get; set; }
        public string ContactAddress { get; set; }
        public string CellPhone { get; set; }
        public string HomePhone { get; set; }
        public string Email { get; set; }
        public string Skype { get; set; }
        public string Yahoo { get; set; }
        public string Facebook { get; set; }
        public string IDCard { get; set; }
        public Nullable<System.DateTime> IDCardDate { get; set; }
        public string IDCardPlace { get; set; }
        public string TaxNo { get; set; }
        public string BankCode { get; set; }
        public string BankName { get; set; }
        public string InsuranceCode { get; set; }
        public Nullable<System.DateTime> InsuranceDate { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> EducationID { get; set; }
        public Nullable<int> DegreeID { get; set; }
        public Nullable<int> EthnicID { get; set; }
        public Nullable<int> ReligionID { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public Nullable<int> Department_PositionID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string Origin { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string Qualification { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string BloodType { get; set; }
        public Nullable<bool> MarriageStatus { get; set; }
        public Nullable<int> KhuVucID { get; set; }
        public string Note { get; set; }
        public Nullable<int> QuanHeID { get; set; }
        public string LoaiQuanHe { get; set; }
        public string DiaChiTiengAnh { get; set; }
        public Nullable<bool> SSDD { get; set; }
        public string GhiChuSSDD { get; set; }
        public Nullable<int> SoNguoiPhuThuoc { get; set; }
        public Nullable<int> HeDaoTaoID { get; set; }
        public Nullable<int> TrinhDoAnhVanID { get; set; }
        public Nullable<int> TrinhDoViTinhID { get; set; }
        public string ThoiGianTotNghiep { get; set; }
        public string SDTNguoiThan { get; set; }
        public Nullable<int> MainAddress_Xa { get; set; }
        public Nullable<int> MainAddress_Huyen { get; set; }
        public Nullable<int> MainAddress_Tinh { get; set; }
        public Nullable<int> ContactAddress_Xa { get; set; }
        public Nullable<int> ContactAddress_Huyen { get; set; }
        public Nullable<int> ContactAddress_Tinh { get; set; }
        public Nullable<int> Origin_Xa { get; set; }
        public Nullable<int> Origin_Huyen { get; set; }
        public Nullable<int> Origin_Tinh { get; set; }
        public int EmploymentHistoryID { get; set; }
        public Nullable<System.DateTime> DecisionDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<int> CategoryDecisionID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<int> InternshipPosition { get; set; }
        public string NoteQTCT { get; set; }
        public Nullable<int> PerPosition { get; set; }
        public Nullable<int> PerPlurality { get; set; }
        public Nullable<System.DateTime> NgayXuongTau { get; set; }
        public Nullable<bool> XacNhan { get; set; }
        public Nullable<int> DecisionNo { get; set; }
        public Nullable<int> LyDoNghiViec_ID { get; set; }
        public Nullable<double> Salary { get; set; }
        public Nullable<double> AllowanceSalary { get; set; }
        public Nullable<double> Bonus { get; set; }
        public Nullable<double> AllowanceBonus { get; set; }
        public Nullable<double> SalaryPlurality { get; set; }
        public Nullable<double> AllowanceSalaryPlurality { get; set; }
        public Nullable<double> BonusPlurality { get; set; }
        public Nullable<double> AllowanceBonusPlurality { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> SoNgay { get; set; }
        public string TGDT { get; set; }
        public string QTDT { get; set; }
        public string EducationName { get; set; }
        public string ChucVu { get; set; }
    }
}
