//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewHopDongGanNhat
    {
        public int ContractHistoryID { get; set; }
        public Nullable<int> ContractTypeID { get; set; }
        public string ContractNo { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public Nullable<System.DateTime> EffctiveDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<int> PositionID { get; set; }
    }
}
