//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewNhanVienTongHop
    {
        public Nullable<int> EmployeeID { get; set; }
        public string EmployeeCode { get; set; }
        public string CardNo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Alias { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string BirthPlace { get; set; }
        public string MainAddress { get; set; }
        public string ContactAddress { get; set; }
        public string CellPhone { get; set; }
        public string HomePhone { get; set; }
        public string Email { get; set; }
        public string Skype { get; set; }
        public string Yahoo { get; set; }
        public string Facebook { get; set; }
        public string IDCard { get; set; }
        public Nullable<System.DateTime> IDCardDate { get; set; }
        public string IDCardPlace { get; set; }
        public string TaxNo { get; set; }
        public string BankCode { get; set; }
        public string BankName { get; set; }
        public string InsuranceCode { get; set; }
        public Nullable<System.DateTime> InsuranceDate { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> EducationID { get; set; }
        public Nullable<int> DegreeID { get; set; }
        public Nullable<int> EthnicID { get; set; }
        public Nullable<int> ReligionID { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public Nullable<int> Department_PositionID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string Origin { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string Qualification { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string BloodType { get; set; }
        public Nullable<bool> MarriageStatus { get; set; }
        public Nullable<int> KhuVucID { get; set; }
        public string Note { get; set; }
        public Nullable<int> QuanHeID { get; set; }
        public string LoaiQuanHe { get; set; }
        public string DiaChiTiengAnh { get; set; }
        public Nullable<bool> SSDD { get; set; }
        public string GhiChuSSDD { get; set; }
        public Nullable<int> SoNguoiPhuThuoc { get; set; }
        public Nullable<int> HeDaoTaoID { get; set; }
        public Nullable<int> TrinhDoAnhVanID { get; set; }
        public Nullable<int> TrinhDoViTinhID { get; set; }
        public string ThoiGianTotNghiep { get; set; }
        public string SDTNguoiThan { get; set; }
        public Nullable<int> MainAddress_Xa { get; set; }
        public Nullable<int> MainAddress_Huyen { get; set; }
        public Nullable<int> MainAddress_Tinh { get; set; }
        public Nullable<int> ContactAddress_Xa { get; set; }
        public Nullable<int> ContactAddress_Huyen { get; set; }
        public Nullable<int> ContactAddress_Tinh { get; set; }
        public Nullable<int> Origin_Xa { get; set; }
        public Nullable<int> Origin_Huyen { get; set; }
        public Nullable<int> Origin_Tinh { get; set; }
        public Nullable<System.DateTime> NgaySSDD { get; set; }
        public int EmploymentHistoryID { get; set; }
        public Nullable<System.DateTime> DecisionDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string ContentDecision { get; set; }
        public Nullable<int> CategoryDecisionID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public string ChucVu { get; set; }
        public Nullable<int> PluralityID { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> ThuTuPhongBan { get; set; }
        public string SchoolName { get; set; }
        public string Description { get; set; }
        public string MainAddressPhuongXa { get; set; }
        public string MainAddressQuanHuyen { get; set; }
        public string MainAddressTinhThanhPho { get; set; }
        public string TenTrinhDoViTinh { get; set; }
        public string TenTrinhDoAnhVan { get; set; }
        public string ContactAddressPhuongXa { get; set; }
        public string ContactAddressQuanHuyen { get; set; }
        public string ContactAddressTinhThanhPho { get; set; }
        public string OriginPhuongXa { get; set; }
        public string OriginQuanHuyen { get; set; }
        public string OriginTinhThanhPho { get; set; }
        public string TenHeDaoTao { get; set; }
        public string TenKhuVuc { get; set; }
        public string EducationName { get; set; }
    }
}
