//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAuLac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public int EmployeeID { get; set; }
        public string EmployeeCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public string DepartmentName { get; set; }
        public string PositionName { get; set; }
        public Nullable<System.DateTime> DecisionDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<int> CategoryDecisionID { get; set; }
        public Nullable<int> LyDoNghiViec_ID { get; set; }
        public Nullable<int> ContractHistoryID { get; set; }
        public Nullable<int> ContractTypeID { get; set; }
        public string ContractNo { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public Nullable<System.DateTime> EffctiveDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string LyDoNghiViec_Name { get; set; }
        public int EmploymentHistoryID { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string ContractTypeName { get; set; }
        public Nullable<int> GroupContractTypeID { get; set; }
        public string GroupContractTypeName { get; set; }
    }
}
